# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\oxoxo\Diplom\ui\main.ui'
#
# Created: Thu Jun 05 16:15:52 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(716, 683)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 661, 591))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(213, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 110, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 113, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(10, 150, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.pushButton_5 = QtGui.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 150, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(10, 190, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pushButton_12 = QtGui.QPushButton(self.tab)
        self.pushButton_12.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(140, 280, 26, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.widget_2 = QtGui.QWidget(self.tab_2)
        self.widget_2.setGeometry(QtCore.QRect(0, 300, 319, 251))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(331, 9, 321, 251))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(500, 280, 16, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.widget_3 = QtGui.QWidget(self.tab_2)
        self.widget_3.setGeometry(QtCore.QRect(337, 300, 311, 251))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 230, 101, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 206))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_6.setProperty("value", 1.0)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.gridLayout.addWidget(self.doubleSpinBox_6, 0, 1, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_2.setMinimum(-100.0)
        self.doubleSpinBox_2.setMaximum(1000.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setProperty("value", 0.5)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout.addWidget(self.doubleSpinBox_2, 2, 1, 2, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setMinimum(-100.0)
        self.doubleSpinBox.setMaximum(1000.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 1.5)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_3.setMinimum(-100.0)
        self.doubleSpinBox_3.setMaximum(1000.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout.addWidget(self.doubleSpinBox_3, 5, 1, 2, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_4.setMinimum(-100.0)
        self.doubleSpinBox_4.setMaximum(1000.0)
        self.doubleSpinBox_4.setProperty("value", 10.0)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout.addWidget(self.doubleSpinBox_4, 7, 1, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_5.setMinimum(-100.0)
        self.doubleSpinBox_5.setMaximum(10000.0)
        self.doubleSpinBox_5.setSingleStep(100.0)
        self.doubleSpinBox_5.setProperty("value", 100.0)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout.addWidget(self.doubleSpinBox_5, 8, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 2, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 2, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 4, 0, 1, 1)
        self.doubleSpinBox_20 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_20.setProperty("value", 0.05)
        self.doubleSpinBox_20.setObjectName(_fromUtf8("doubleSpinBox_20"))
        self.gridLayout.addWidget(self.doubleSpinBox_20, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox.setMaximum(1000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setProperty("value", 100)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_2.addWidget(self.spinBox, 1, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 230, 111, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 260, 101, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_9 = QtGui.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 260, 111, 21))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_19 = QtGui.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 220, 101, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.widget_4 = QtGui.QWidget(self.tab_3)
        self.widget_4.setGeometry(QtCore.QRect(327, 20, 301, 241))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.widget_5 = QtGui.QWidget(self.tab_3)
        self.widget_5.setGeometry(QtCore.QRect(0, 300, 319, 241))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(140, 280, 26, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.widget_6 = QtGui.QWidget(self.tab_3)
        self.widget_6.setGeometry(QtCore.QRect(327, 300, 311, 241))
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(490, 280, 16, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 32, 221, 181))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.doubleSpinBox_9 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_9.setMinimum(-100.0)
        self.doubleSpinBox_9.setMaximum(1000.0)
        self.doubleSpinBox_9.setSingleStep(0.01)
        self.doubleSpinBox_9.setProperty("value", -0.8)
        self.doubleSpinBox_9.setObjectName(_fromUtf8("doubleSpinBox_9"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_9, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_8.setMinimum(-100.0)
        self.doubleSpinBox_8.setMaximum(1000.0)
        self.doubleSpinBox_8.setSingleStep(0.1)
        self.doubleSpinBox_8.setProperty("value", 0.3)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_8, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_7.setProperty("value", 1.0)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_7, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.doubleSpinBox_10 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_10.setMinimum(-100.0)
        self.doubleSpinBox_10.setMaximum(1000.0)
        self.doubleSpinBox_10.setObjectName(_fromUtf8("doubleSpinBox_10"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_10, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_11.setMinimum(-100.0)
        self.doubleSpinBox_11.setMaximum(1000.0)
        self.doubleSpinBox_11.setProperty("value", 10.0)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_11, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 5, 0, 1, 1)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_12.setMinimum(-100.0)
        self.doubleSpinBox_12.setMaximum(10000.0)
        self.doubleSpinBox_12.setSingleStep(100.0)
        self.doubleSpinBox_12.setProperty("value", 100.0)
        self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_12, 5, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.label_18 = QtGui.QLabel(self.layoutWidget1)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 1, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setProperty("value", 100)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_5.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(120, 220, 111, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_10 = QtGui.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 250, 101, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_3)
        self.pushButton_11.setGeometry(QtCore.QRect(120, 250, 111, 23))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.widget_7 = QtGui.QWidget(self.tab_4)
        self.widget_7.setGeometry(QtCore.QRect(10, 10, 301, 241))
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.widget_8 = QtGui.QWidget(self.tab_4)
        self.widget_8.setGeometry(QtCore.QRect(350, 10, 301, 241))
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.widget_14 = QtGui.QWidget(self.tab_4)
        self.widget_14.setGeometry(QtCore.QRect(10, 270, 301, 251))
        self.widget_14.setObjectName(_fromUtf8("widget_14"))
        self.widget_15 = QtGui.QWidget(self.tab_4)
        self.widget_15.setGeometry(QtCore.QRect(350, 270, 301, 251))
        self.widget_15.setObjectName(_fromUtf8("widget_15"))
        self.pushButton_16 = QtGui.QPushButton(self.tab_4)
        self.pushButton_16.setGeometry(QtCore.QRect(300, 530, 61, 21))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.widget_9 = QtGui.QWidget(self.tab_5)
        self.widget_9.setGeometry(QtCore.QRect(10, 10, 301, 241))
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.widget_10 = QtGui.QWidget(self.tab_5)
        self.widget_10.setGeometry(QtCore.QRect(350, 10, 301, 241))
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.widget_16 = QtGui.QWidget(self.tab_5)
        self.widget_16.setGeometry(QtCore.QRect(10, 270, 301, 261))
        self.widget_16.setObjectName(_fromUtf8("widget_16"))
        self.widget_17 = QtGui.QWidget(self.tab_5)
        self.widget_17.setGeometry(QtCore.QRect(350, 270, 291, 261))
        self.widget_17.setObjectName(_fromUtf8("widget_17"))
        self.pushButton_17 = QtGui.QPushButton(self.tab_5)
        self.pushButton_17.setGeometry(QtCore.QRect(300, 540, 61, 23))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_23 = QtGui.QLabel(self.tab_6)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_6)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 221, 206))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_26 = QtGui.QLabel(self.layoutWidget_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 8, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_6.addWidget(self.label_27, 7, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_6.addWidget(self.label_28, 2, 0, 2, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_6.addWidget(self.label_31, 5, 0, 2, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_6.addWidget(self.label_24, 1, 0, 1, 1)
        self.doubleSpinBox_13 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_13.setProperty("value", 1.0)
        self.doubleSpinBox_13.setObjectName(_fromUtf8("doubleSpinBox_13"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_13, 0, 1, 1, 1)
        self.doubleSpinBox_14 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_14.setMinimum(-100.0)
        self.doubleSpinBox_14.setMaximum(1000.0)
        self.doubleSpinBox_14.setSingleStep(0.1)
        self.doubleSpinBox_14.setProperty("value", 0.5)
        self.doubleSpinBox_14.setObjectName(_fromUtf8("doubleSpinBox_14"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_14, 2, 1, 2, 1)
        self.doubleSpinBox_15 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_15.setMinimum(-100.0)
        self.doubleSpinBox_15.setMaximum(1000.0)
        self.doubleSpinBox_15.setSingleStep(0.01)
        self.doubleSpinBox_15.setProperty("value", 1.0)
        self.doubleSpinBox_15.setObjectName(_fromUtf8("doubleSpinBox_15"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_15, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_6.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 4, 0, 1, 1)
        self.doubleSpinBox_16 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_16.setMinimum(-100.0)
        self.doubleSpinBox_16.setMaximum(1000.0)
        self.doubleSpinBox_16.setProperty("value", 0.25)
        self.doubleSpinBox_16.setObjectName(_fromUtf8("doubleSpinBox_16"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_16, 4, 1, 1, 1)
        self.doubleSpinBox_18 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_18.setMinimum(-100.0)
        self.doubleSpinBox_18.setMaximum(10000.0)
        self.doubleSpinBox_18.setSingleStep(100.0)
        self.doubleSpinBox_18.setProperty("value", 10.0)
        self.doubleSpinBox_18.setObjectName(_fromUtf8("doubleSpinBox_18"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_18, 7, 1, 1, 1)
        self.doubleSpinBox_17 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_17.setMinimum(-100.0)
        self.doubleSpinBox_17.setMaximum(1000.0)
        self.doubleSpinBox_17.setProperty("value", 0.0)
        self.doubleSpinBox_17.setObjectName(_fromUtf8("doubleSpinBox_17"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_17, 5, 1, 2, 1)
        self.doubleSpinBox_19 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_19.setMaximum(1000.0)
        self.doubleSpinBox_19.setProperty("value", 100.0)
        self.doubleSpinBox_19.setObjectName(_fromUtf8("doubleSpinBox_19"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_19, 8, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 0, 0, 1, 2)
        self.label_32 = QtGui.QLabel(self.layoutWidget_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_4.addWidget(self.label_32, 1, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setSingleStep(10)
        self.spinBox_3.setProperty("value", 100)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_4.addWidget(self.spinBox_3, 1, 1, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.tab_6)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 240, 101, 23))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.tab_6)
        self.pushButton_14.setGeometry(QtCore.QRect(120, 240, 111, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.tab_6)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 270, 101, 23))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.widget_11 = QtGui.QWidget(self.tab_6)
        self.widget_11.setGeometry(QtCore.QRect(330, 20, 321, 241))
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.widget_12 = QtGui.QWidget(self.tab_6)
        self.widget_12.setGeometry(QtCore.QRect(10, 310, 301, 241))
        self.widget_12.setObjectName(_fromUtf8("widget_12"))
        self.widget_13 = QtGui.QWidget(self.tab_6)
        self.widget_13.setGeometry(QtCore.QRect(330, 310, 311, 241))
        self.widget_13.setObjectName(_fromUtf8("widget_13"))
        self.label_34 = QtGui.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(130, 290, 46, 13))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.tab_6)
        self.label_35.setGeometry(QtCore.QRect(490, 290, 46, 13))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.pushButton_3 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 0, 121, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Моделирование финанcовых процеccов, опиcываемых cтохаcтичеcкими дифференциальными уравнениЯми", None))
        self.pushButton_2.setText(_translate("MainWindow", "ОК", None))
        self.label_9.setText(_translate("MainWindow", "Выбрать модель dx = a(b-x)dt+cdw", None))
        self.label_30.setText(_translate("MainWindow", "Выбрать модель dx = axdt+bxdw", None))
        self.pushButton_5.setText(_translate("MainWindow", "ОК", None))
        self.label_20.setText(_translate("MainWindow", "Моделирование финанcовых процеccов, опиcываемых cтохаcтичеcкими дифференциальными уравнениЯми", None))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>Выбрать модель dx = a(b-x)dt+cx<span style=\" vertical-align:super;\">1/2</span>dw</p></body></html>", None))
        self.pushButton_12.setText(_translate("MainWindow", "OK", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ГлавнаЯ", None))
        self.label_7.setText(_translate("MainWindow", "mean", None))
        self.label_8.setText(_translate("MainWindow", "std", None))
        self.label.setText(_translate("MainWindow", "dx = a(b-x)dt + cdw", None))
        self.pushButton.setText(_translate("MainWindow", "ОК", None))
        self.label_2.setText(_translate("MainWindow", "Введите a :", None))
        self.label_10.setText(_translate("MainWindow", "Введите x0 :", None))
        self.label_6.setText(_translate("MainWindow", "Введите n :", None))
        self.label_5.setText(_translate("MainWindow", "Введите t1 :", None))
        self.label_3.setText(_translate("MainWindow", "Введите b :", None))
        self.label_4.setText(_translate("MainWindow", "Введите t0 :", None))
        self.label_36.setText(_translate("MainWindow", "Введите c:", None))
        self.label_11.setText(_translate("MainWindow", "Введите кол-во траекторий s:", None))
        self.pushButton_7.setText(_translate("MainWindow", "Сохранить в файл", None))
        self.pushButton_6.setText(_translate("MainWindow", "Очиcтить", None))
        self.pushButton_9.setText(_translate("MainWindow", "Сравнить c теорией", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Модель 1", None))
        self.label_19.setText(_translate("MainWindow", "dx = axdt + bxdw", None))
        self.pushButton_4.setText(_translate("MainWindow", "ОК", None))
        self.label_21.setText(_translate("MainWindow", "mean", None))
        self.label_29.setText(_translate("MainWindow", "std", None))
        self.label_12.setText(_translate("MainWindow", "Введите a :", None))
        self.label_16.setText(_translate("MainWindow", "Введите b :", None))
        self.label_13.setText(_translate("MainWindow", "Введите x0 :", None))
        self.label_17.setText(_translate("MainWindow", "Введите t0 :", None))
        self.label_15.setText(_translate("MainWindow", "Введите t1 :", None))
        self.label_14.setText(_translate("MainWindow", "Введите n :", None))
        self.label_18.setText(_translate("MainWindow", "Введите кол-во траекторий s:", None))
        self.pushButton_8.setText(_translate("MainWindow", "Сохранить в файл", None))
        self.pushButton_10.setText(_translate("MainWindow", "Очиcтить", None))
        self.pushButton_11.setText(_translate("MainWindow", "Сравнить c теорией", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Модель 2", None))
        self.pushButton_16.setText(_translate("MainWindow", "Cохранить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Модель 1 - теориЯ", None))
        self.pushButton_17.setText(_translate("MainWindow", "Cохранить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Модель 2 - теориЯ", None))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>dx = a(b-x)dt+cx<span style=\" vertical-align:super;\">1/2</span>dw</p></body></html>", None))
        self.label_26.setText(_translate("MainWindow", "Введите n :", None))
        self.label_27.setText(_translate("MainWindow", "Введите t1 :", None))
        self.label_28.setText(_translate("MainWindow", "Введите b :", None))
        self.label_31.setText(_translate("MainWindow", "Введите t0 :", None))
        self.label_24.setText(_translate("MainWindow", "Введите a :", None))
        self.label_25.setText(_translate("MainWindow", "Введите x0 :", None))
        self.label_33.setText(_translate("MainWindow", "Введите c:", None))
        self.label_32.setText(_translate("MainWindow", "Введите кол-во траекторий s:", None))
        self.pushButton_13.setText(_translate("MainWindow", "OK", None))
        self.pushButton_14.setText(_translate("MainWindow", "Cохранить в файл", None))
        self.pushButton_15.setText(_translate("MainWindow", "Очиcтить", None))
        self.label_34.setText(_translate("MainWindow", "mean", None))
        self.label_35.setText(_translate("MainWindow", "std", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Модель 3", None))
        self.pushButton_3.setText(_translate("MainWindow", "на главную", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

